// declare module 'vuesax';
// declare module 'vue-backtotop'
// declare module 'vue2-hammer';
// declare module 'vue-backtotop';
// declare module 'vue-perfect-scrollbar'
// declare module 'vue-wait';
// declare module 'epic-spinners';
// declare module 'downloadjs';
// declare module 'vue2-dropzone';
// declare module 'dropzone';
